FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y automake libtool pkg-config build-essential gperf flex bison texinfo git

ADD . /repo
WORKDIR /repo
RUN autoreconf -i
RUN ./configure
RUN make -j8
