FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y automake libtool pkg-config build-essential gperf flex bison texinfo git

COPY . /repo
WORKDIR /repo
RUN autoreconf -i
RUN ./configure --prefix=/install
RUN make -j8
RUN make install

FROM ubuntu:20.04 as package
COPY --from=builder /repo/src/dsort /
